name: Deploy UI
# This comment is for pushing a change to a branch to test a github action
on:
  push:
    branches:
      - development
      - derek-task1-sprint4
env:
  AZURE_WEBAPP_PACKAGE_PATH: ui/
  NODE_VERSION: '10.x'
  CI: false

jobs:
  build-and-deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: npm install and build
        run: |
          cd ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          npm install
          npm run build
      - name: Upload To Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/build
          container_name: $web
          connection_string: ${{secrets.BLOB_STORAGE_CONNECTION_STRING}}
